services:
  beacon_node:
    image: sigp/lighthouse:latest
    volumes:
      - ./lighthouse-data:/data
      - ./scripts:/root/scripts:ro
      - ./jwt.txt:/jwt.txt
    ports:
      - 5052:5052/tcp
      - 5053:5053/tcp
      - 5054:5054/tcp
      - 9000:9000/tcp
      - 9000:9000/udp
    command: sh /root/scripts/start-beacon-node.sh
    restart: on-failure
  geth:
    image: ethereum/client-go:latest
    entrypoint: /bin/sh
    volumes:
      - ./geth-data:/data
      - ./scripts:/root/scripts:ro
      - ./jwt.txt:/jwt.txt
    ports:
      - 30303:30303/tcp
      - 30303:30303/udp
      - "127.0.0.1:8545:8545"
    command: /root/scripts/start-geth.sh
    restart: on-failure
